name: Pull Request
on: [pull_request]
jobs:
  tests:
    uses: opay/shared-configs/.github/workflows/app_testing.yml@main
    with:
      config_path: PATH_TO_CONFIG_DIRECTORY
      database_path: PATH_TO_DATABASE
    secrets:
      auth_json: AUTH_JSON_FILE_BODY
