name: Pull Request
on: [pull_request]
jobs:
  tests:
    uses: opay/shared-configs/.github/workflows/app_pull_request.yml@main
    with:
      load_script_path: PATH_TO_LOAD_SCRIPT
      config_path: PATH_TO_CONFIG_DIRECTORY
      database_path: PATH_TO_DATABASE
    secrets:
      auth_secret: AUTH_SECRET